### `columnar data `

- Series (1D)
- DataFrame (2D,nd): (like collection of series)

In [196]:
import numpy as np 
import pandas as pd 

## Creating a 1D Series with custom labels 

prices = pd.Series([49.99,19.99,99.99],name="price", index=["p1","p2","p3"])
prices

p1    49.99
p2    19.99
p3    99.99
Name: price, dtype: float64

In [197]:
data = {
    "product_id": [101,102,103],
    "category": ["Electronics","Books", "Electronics"],
    "price":[49.99,19.99,99.99],
    "in_stock": [True, False, True],
}

df = pd.DataFrame(data,index=["p1","p2","p3"])
df

    product_id     category  price  in_stock
p1         101  Electronics  49.99      True
p2         102        Books  19.99     False
p3         103  Electronics  99.99      True

In [198]:
prices["p1"]

np.float64(49.99)

In [199]:
df["price"]["p3"]

np.float64(99.99)

In [200]:
###

In [201]:
df = pd.read_csv(
    "raw_customer_data.csv",
    usecols=['user_id', 'signup_date', 'monthly_spend', 'churn_label'], 
    parse_dates=["signup_date"],
    na_values=["N/A","missing","NONE","-999"]
)

mem_mb = df.memory_usage(deep=True).sum()/1e6
print(f"Memory Footprint: {mem_mb:.5f} MB")

Memory Footprint: 0.00183 MB

In [202]:
df

     user_id signup_date  monthly_spend churn_label
0   USR_1000  2024-01-01         140.54       False
1   USR_1001  2024-01-02         333.32       False
2   USR_1002  2024-01-03         260.67       False
3   USR_1003  2024-01-04         215.11        True
4   USR_1004  2024-01-05          67.31       False
5   USR_1005  2024-01-06            NaN       False
6   USR_1006  2024-01-07          32.72        True
7   USR_1007  2024-01-08         272.24       False
8   USR_1008  2024-01-09         216.34       False
9   USR_1009  2024-01-10         250.77       False
10  USR_1010  2024-01-11          22.25        True
11  USR_1011  2024-01-12         339.81       False
12  USR_1012  2024-01-13            NaN         NaN
13  USR_1013  2024-01-14          87.05       False
14  USR_1014  2024-01-15          83.47       False
15  USR_1015  2024-01-16          87.72       False
16  USR_1016  2024-01-17         118.66       False
17  USR_1017  2024-01-18         190.22       False
18  USR_1018  2024-01-19         160.29        True
19  USR_1019  2024-01-20         119.23       False
20  USR_1020  2024-01-21         220.10       False
21  USR_1021  2024-01-22         221.75        True
22  USR_1022  2024-01-23         120.21       False
23  USR_1023  2024-01-24            NaN       False
24  USR_1024  2024-01-25         167.32       False

1. df.head(n) / df.tail(n)
2. df.shape: returns (rows, cols) 
3. df.info()
4. df.describe(): Stats summary
5. df.dtypes

In [203]:
import pandas as pd 

def inspect_dataset( dataframe: pd.DataFrame) -> None:
    """Production fn"""

    print(f"=== SHAPE: {dataframe.shape[0]} rows, {dataframe.shape[1]} cols ===")

    summary = pd.DataFrame({
        "Dtype": dataframe.dtypes,
        "Null Count": dataframe.isna().sum(),
        "Null %": (dataframe.isna().sum() / len(dataframe)) * 100,
    })
    stats_summary = pd.DataFrame(dataframe.describe())

    print("\n=== DATA PROFILE ===")
    print(summary)
    print("\n\n=== Stats Summary === \n",stats_summary)

inspect_dataset(df)

=== SHAPE: 25 rows, 4 cols ===

=== DATA PROFILE ===
                        Dtype  Null Count  Null %
user_id                   str           0     0.0
signup_date    datetime64[us]           0     0.0
monthly_spend         float64           3    12.0
churn_label            object           1     4.0


=== Stats Summary ===
                signup_date  monthly_spend
count                   25      22.000000
mean   2024-01-13 00:00:00     169.413636
min    2024-01-01 00:00:00      22.250000
25%    2024-01-07 00:00:00      95.455000
50%    2024-01-13 00:00:00     163.805000
75%    2024-01-19 00:00:00     221.337500
max    2024-01-25 00:00:00     339.810000
std                    NaN      90.369456

In [204]:
sales_df = pd.read_csv("sales_cohort_data.csv")

In [205]:
inspect_dataset(sales_df)

=== SHAPE: 200 rows, 8 cols ===

=== DATA PROFILE ===
                    Dtype  Null Count  Null %
order_id              str           0     0.0
customer_id           str           0     0.0
order_date            str           0     0.0
region                str           0     0.0
category              str           0     0.0
customer_segment      str           0     0.0
sales_amount      float64           0     0.0
discount          float64          17     8.5


=== Stats Summary ===
        sales_amount    discount
count    200.000000  183.000000
mean     399.738950    0.056557
std      300.340069    0.062552
min       10.580000    0.000000
25%      144.337500    0.000000
50%      341.795000    0.050000
75%      537.065000    0.100000
max     1189.680000    0.200000

In [206]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   user_id        25 non-null     str
 1   signup_date    25 non-null     datetime64[us]
 2   monthly_spend  22 non-null     float64
 3   churn_label    24 non-null     object
dtypes: datetime64[us](1), float64(1), object(1), str(1)
memory usage: 1.1+ KB

In [207]:
df.dtypes

user_id                     str
signup_date      datetime64[us]
monthly_spend           float64
churn_label              object
dtype: object

In [208]:
df.head(5)

    user_id signup_date  monthly_spend churn_label
0  USR_1000  2024-01-01         140.54       False
1  USR_1001  2024-01-02         333.32       False
2  USR_1002  2024-01-03         260.67       False
3  USR_1003  2024-01-04         215.11        True
4  USR_1004  2024-01-05          67.31       False

In [209]:
df.tail(5)

     user_id signup_date  monthly_spend churn_label
20  USR_1020  2024-01-21         220.10       False
21  USR_1021  2024-01-22         221.75        True
22  USR_1022  2024-01-23         120.21       False
23  USR_1023  2024-01-24            NaN       False
24  USR_1024  2024-01-25         167.32       False

In [210]:
df.shape

(25, 4)

In [211]:
df.describe()

               signup_date  monthly_spend
count                   25      22.000000
mean   2024-01-13 00:00:00     169.413636
min    2024-01-01 00:00:00      22.250000
25%    2024-01-07 00:00:00      95.455000
50%    2024-01-13 00:00:00     163.805000
75%    2024-01-19 00:00:00     221.337500
max    2024-01-25 00:00:00     339.810000
std                    NaN      90.369456

## `df.loc[row_label, col_label]`
    Label-based indexing. Uses explict columns names and index labels.
    Highly readable and standard in production

## `df.iloc[row_index, col_index]`
    Integer position-based indexing (0,1,...N-1). Slicing behaves like standard python list ( upper bound excluded)

In [212]:
# 1. label-based slicing
high_spenders = df.loc[df['monthly_spend'] > 100,["user_id","churn_label"]]

high_spenders

     user_id churn_label
0   USR_1000       False
1   USR_1001       False
2   USR_1002       False
3   USR_1003        True
7   USR_1007       False
8   USR_1008       False
9   USR_1009       False
11  USR_1011       False
16  USR_1016       False
17  USR_1017       False
18  USR_1018        True
19  USR_1019       False
20  USR_1020       False
21  USR_1021        True
22  USR_1022       False
24  USR_1024       False

In [213]:
# Integer Positional Slicing --> First 10 rows, first 3 columns
first_10_rows = df.iloc[0:10,0:3]

first_10_rows

    user_id signup_date  monthly_spend
0  USR_1000  2024-01-01         140.54
1  USR_1001  2024-01-02         333.32
2  USR_1002  2024-01-03         260.67
3  USR_1003  2024-01-04         215.11
4  USR_1004  2024-01-05          67.31
5  USR_1005  2024-01-06            NaN
6  USR_1006  2024-01-07          32.72
7  USR_1007  2024-01-08         272.24
8  USR_1008  2024-01-09         216.34
9  USR_1009  2024-01-10         250.77

In [214]:
# Compound Boolean Logic ( & = AND, |= OR, ~ = NOT)
## Boolean masking
target_cohort = df.loc[
    (df["monthly_spend"]>50) & (df["churn_label"] == False),
    ["user_id","signup_date"]
]

target_cohort

     user_id signup_date
0   USR_1000  2024-01-01
1   USR_1001  2024-01-02
2   USR_1002  2024-01-03
4   USR_1004  2024-01-05
7   USR_1007  2024-01-08
8   USR_1008  2024-01-09
9   USR_1009  2024-01-10
11  USR_1011  2024-01-12
13  USR_1013  2024-01-14
14  USR_1014  2024-01-15
15  USR_1015  2024-01-16
16  USR_1016  2024-01-17
17  USR_1017  2024-01-18
19  USR_1019  2024-01-20
20  USR_1020  2024-01-21
22  USR_1022  2024-01-23
24  USR_1024  2024-01-25

1. MCAR
2. MAR
3. MNAR

In [215]:
# Detecting and Summarizing Nulls in pandas 
df.isna().sum()

user_id          0
signup_date      0
monthly_spend    3
churn_label      1
dtype: int64

In [216]:
# Percent missing calculation 
missing_pct = (df.isna().sum()/len(df)) * 100
missing_pct

user_id           0.0
signup_date       0.0
monthly_spend    12.0
churn_label       4.0
dtype: float64

## Remediation Decision Frameworkabs
1. Missingness > 40-50%: Drop column entirely(`df.drop(columns=['col'])`) to avoid synthetic bias
2. Missingness < 5% (MCAR): Drop affected rows(`df.dropna(subset=['col'])`). Minimal impact on statistical distribution
3. Numerical Imputation: Impute missing entries with median (robust to outlier ) or median
4. Categorical Imputation: Impute missing entries with column Mode (most freq value) or 'unknown'

In [217]:
df_clean = df.dropna(subset=["user_id"])
df_clean

     user_id signup_date  monthly_spend churn_label
0   USR_1000  2024-01-01         140.54       False
1   USR_1001  2024-01-02         333.32       False
2   USR_1002  2024-01-03         260.67       False
3   USR_1003  2024-01-04         215.11        True
4   USR_1004  2024-01-05          67.31       False
5   USR_1005  2024-01-06            NaN       False
6   USR_1006  2024-01-07          32.72        True
7   USR_1007  2024-01-08         272.24       False
8   USR_1008  2024-01-09         216.34       False
9   USR_1009  2024-01-10         250.77       False
10  USR_1010  2024-01-11          22.25        True
11  USR_1011  2024-01-12         339.81       False
12  USR_1012  2024-01-13            NaN         NaN
13  USR_1013  2024-01-14          87.05       False
14  USR_1014  2024-01-15          83.47       False
15  USR_1015  2024-01-16          87.72       False
16  USR_1016  2024-01-17         118.66       False
17  USR_1017  2024-01-18         190.22       False
18  USR_1018  2024-01-19         160.29        True
19  USR_1019  2024-01-20         119.23       False
20  USR_1020  2024-01-21         220.10       False
21  USR_1021  2024-01-22         221.75        True
22  USR_1022  2024-01-23         120.21       False
23  USR_1023  2024-01-24            NaN       False
24  USR_1024  2024-01-25         167.32       False

In [218]:
spend_median = df["monthly_spend"].median()
df['monthly_spend'] = df["monthly_spend"].fillna(spend_median)

In [219]:
# cat_mode = df["category"].mode()[0]
# df["category"] = df["category"].fillna(cat_mode)

In [220]:
# Strategy C: Forward fill for timeseries
## use ffill and bfill in date_range
# df["sensor_reading"] = df["sensor_reading"].ffill().bfill()

## Data Type casting and Memory footprint Optimization

In [221]:
df = pd.read_csv("dirty_transactions.csv", na_values=["NA", "null", "-999"])

In [222]:
df["transaction_date"] = pd.to_datetime(df["transaction_date"])
df["state"] = df["state"].astype("category")

In [223]:
df["amount"] = df["amount"].fillna(df.groupby("customer_segment")["amount"].transform("median"))

In [224]:
df_clean = df.loc[df["amount"] >= 0.0].copy()

In [225]:
df_clean.sample(5)

   transaction_id customer_segment    transaction_date state    amount
7        TXN_5007              SMB 2024-05-04 12:00:00    TX   410.800
11       TXN_5011       Enterprise 2024-05-06 12:00:00    NY  1911.175
15       TXN_5015         Consumer 2024-05-08 12:00:00    IL    15.500
4        TXN_5004              SMB 2024-05-03 00:00:00    CA   360.250
19       TXN_5019              SMB 2024-05-10 12:00:00    FL   380.000

### Split apply-combine paradigm 
- Core Operations of Data Aggregation
  1. Split
  2. Apply
  3. Combine

In [226]:
import pandas as pd 
df = pd.read_csv("sales_cohort_data.csv")

In [227]:
df.head()

,order_id,customer_id,order_date,region,category,customer_segment,sales_amount,discount
0,ORD_10000,CUST_131,2024-01-01,West,Technology,SMB,594.27,NaN
1,ORD_10001,CUST_111,2024-01-02,East,Furniture,Consumer,234.70,0.00
2,ORD_10002,CUST_117,2024-01-03,East,Technology,SMB,847.50,0.00
3,ORD_10003,CUST_106,2024-01-04,East,Furniture,SMB,560.86,0.15
4,ORD_10004,CUST_123,2024-01-05,West,Furniture,SMB,369.73,0.05

In [228]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          200 non-null    str
 1   customer_id       200 non-null    str
 2   order_date        200 non-null    str
 3   region            200 non-null    str
 4   category          200 non-null    str
 5   customer_segment  200 non-null    str
 6   sales_amount      200 non-null    float64
 7   discount          183 non-null    float64
dtypes: float64(2), str(6)
memory usage: 22.1 KB

In [229]:
df.isna().sum()

order_id             0
customer_id          0
order_date           0
region               0
category             0
customer_segment     0
sales_amount         0
discount            17
dtype: int64

In [230]:
df.describe()

       sales_amount    discount
count    200.000000  183.000000
mean     399.738950    0.056557
std      300.340069    0.062552
min       10.580000    0.000000
25%      144.337500    0.000000
50%      341.795000    0.050000
75%      537.065000    0.100000
max     1189.680000    0.200000

In [231]:
region_sales = df.groupby("region")["sales_amount"].mean()

In [232]:
region_sales

region
East     413.868837
North    387.849592
South    375.271639
West     430.962340
Name: sales_amount, dtype: float64

In [233]:
cat_region = df.groupby(["category","region"])["sales_amount"].sum()

In [234]:
cat_region

category         region
Furniture        East       6709.96
                 North      5982.39
                 South     10013.60
                 West       5194.94
Office Supplies  East        658.87
                 North      1043.10
                 South      1221.28
                 West       1211.94
Technology       East      10427.53
                 North     11979.14
                 South     11656.69
                 West      13848.35
Name: sales_amount, dtype: float64

In [235]:
pivoted_view = cat_region.unstack(level="region")

In [236]:
pivoted_view

region               East     North     South      West
category
Furniture         6709.96   5982.39  10013.60   5194.94
Office Supplies    658.87   1043.10   1221.28   1211.94
Technology       10427.53  11979.14  11656.69  13848.35

### Modern Named Aggregations (.agg())

In [237]:
exec_summary = df.groupby("region").agg(
    total_revenue = ("sales_amount","sum"),
    avg_order_val = ("sales_amount", "mean"),
    unique_customers = ("customer_id","nunique"),
    max_discount = ("discount","max")
).reset_index()

In [238]:
exec_summary

  region  total_revenue  avg_order_val  unique_customers  max_discount
0   East       17796.36     413.868837                32           0.2
1  North       19004.63     387.849592                31           0.2
2  South       22891.57     375.271639                37           0.2
3   West       20255.23     430.962340                31           0.2

### Group Transformations (.transform()

In [239]:
df['cat_avg_sales'] = df.groupby("category")["sales_amount"].transform("mean")

In [240]:
df.head()

,order_id,customer_id,order_date,region,category,customer_segment,sales_amount,discount,cat_avg_sales
0,ORD_10000,CUST_131,2024-01-01,West,Technology,SMB,594.27,NaN,656.324795
1,ORD_10001,CUST_111,2024-01-02,East,Furniture,Consumer,234.70,0.00,357.703718
2,ORD_10002,CUST_117,2024-01-03,East,Technology,SMB,847.50,0.00,656.324795
3,ORD_10003,CUST_106,2024-01-04,East,Furniture,SMB,560.86,0.15,357.703718
4,ORD_10004,CUST_123,2024-01-05,West,Furniture,SMB,369.73,0.05,357.703718

In [241]:
df["region_avg"] = df.groupby("region")["sales_amount"].transform("mean")

In [242]:
df["dev_from_avg"] = df["sales_amount"] - df["region_avg"]

In [243]:
df.sample(5)

,order_id,customer_id,order_date,region,category,customer_segment,sales_amount,discount,cat_avg_sales,region_avg,dev_from_avg
5,ORD_10005,CUST_111,2024-01-06,South,Office Supplies,Consumer,20.79,NaN,84.391633,375.271639,-354.481639
171,ORD_10171,CUST_106,2024-06-20,West,Office Supplies,SMB,20.77,0.0,84.391633,430.962340,-410.192340
128,ORD_10128,CUST_111,2024-05-08,West,Furniture,Enterprise,229.20,0.0,357.703718,430.962340,-201.762340
153,ORD_10153,CUST_124,2024-06-02,North,Furniture,Enterprise,317.61,0.0,357.703718,387.849592,-70.239592
149,ORD_10149,CUST_140,2024-05-29,North,Technology,Enterprise,535.60,NaN,656.324795,387.849592,147.750408

In [244]:
df["discount"] = df["discount"].fillna(
    df.groupby("customer_segment")["discount"].transform("median")
)

In [245]:
df.sample(5)

,order_id,customer_id,order_date,region,category,customer_segment,sales_amount,discount,cat_avg_sales,region_avg,dev_from_avg
46,ORD_10046,CUST_146,2024-02-16,West,Technology,Consumer,989.30,0.10,656.324795,430.962340,558.337660
26,ORD_10026,CUST_108,2024-01-27,West,Office Supplies,SMB,140.97,0.00,84.391633,430.962340,-289.992340
133,ORD_10133,CUST_118,2024-05-13,East,Technology,Enterprise,527.66,0.10,656.324795,413.868837,113.791163
182,ORD_10182,CUST_121,2024-07-01,South,Furniture,SMB,498.85,0.00,357.703718,375.271639,123.578361
12,ORD_10012,CUST_128,2024-01-13,East,Office Supplies,SMB,10.58,0.05,84.391633,413.868837,-403.288837

### Reshaping: `pivot_table()` & `crosstab()`
1. `pivot_table():` Multi-dimensional aggregations for numerical data.
2. `crosstab():` Freq counts and cross-tabulations across categorical dimensions

In [246]:
pivot_df = pd.pivot_table(
    df, values="sales_amount",
    index="customer_segment", columns="category",
    aggfunc="mean", 
    fill_value=0.0, margins=True
)

In [247]:
pivot_df

category           Furniture  Office Supplies  Technology         All
customer_segment
Consumer          337.775926        81.896667  665.977692  421.817385
Enterprise        385.418182        92.366000  718.844500  496.125957
SMB               355.232414        84.081250  600.718519  331.951591
All               357.703718        84.391633  656.324795  399.738950

In [250]:
freq_table = pd.crosstab(
    index=df["region"],
    columns=df["customer_segment"],
    normalize="index" # Normalize by dividing all values by the sum of values.
)

In [251]:
freq_table

customer_segment  Consumer  Enterprise       SMB
region
East              0.255814    0.395349  0.348837
North             0.326531    0.224490  0.448980
South             0.409836    0.147541  0.442623
West              0.276596    0.212766  0.510638

### Unpivoting Data with melt()

In [255]:
wide_df = pd.DataFrame({
    "Product": ["A","B"],
    "2024": [100, 300],
    "2025": [150,350]
})
wide_df

  Product  2024  2025
0       A   100   150
1       B   300   350

In [256]:
long_df = pd.melt(
    wide_df, 
    id_vars=["Product"],
    value_vars=["2024","2025"],
    var_name="Year",
    value_name="Sales"
)

In [257]:
long_df

  Product  Year  Sales
0       A  2024    100
1       B  2024    300
2       A  2025    150
3       B  2025    350

## The 4-Step EDA blueprint 

1. `Phase 1:` Structural Audit
2. `Phase 2:` Univariate Analysis
3. `Phase 3:` Bivariate & Multivariate Analysis
4. `Phase 4:` Business Insights & Anomaly Investigation

In [266]:
numeric_cols = df.select_dtypes("number")
numeric_cols

     sales_amount  discount  cat_avg_sales  region_avg  dev_from_avg
0          594.27      0.05     656.324795  430.962340    163.307660
1          234.70      0.00     357.703718  413.868837   -179.168837
2          847.50      0.00     656.324795  413.868837    433.631163
3          560.86      0.15     357.703718  413.868837    146.991163
4          369.73      0.05     357.703718  430.962340    -61.232340
..            ...       ...            ...         ...           ...
195        479.84      0.10     656.324795  375.271639    104.568361
196        217.12      0.10     357.703718  375.271639   -158.151639
197        268.44      0.15     357.703718  375.271639   -106.831639
198        502.80      0.10     357.703718  375.271639    127.528361
199        163.72      0.00     357.703718  413.868837   -250.148837

[200 rows x 5 columns]

In [263]:
Q1 = df["sales_amount"].quantile(0.25)
Q3 = df["sales_amount"].quantile(0.75) 
IQR = Q3 - Q1

In [280]:
IQR

np.float64(392.7275000000001)

In [279]:
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

In [278]:
lower

np.float64(-444.7537500000002)

In [267]:
outliers = df.loc[
    (df["sales_amount"] < lower) | (df["sales_amount"] > upper)
]

In [269]:
print(f"Detected {len(outliers)} outliers")

Detected 7 outliers

In [276]:
outliers.sample(5)

,order_id,customer_id,order_date,region,category,customer_segment,sales_amount,discount,cat_avg_sales,region_avg,dev_from_avg
76,ORD_10076,CUST_137,2024-03-17,West,Technology,SMB,1168.42,0.0,656.324795,430.962340,737.457660
120,ORD_10120,CUST_117,2024-04-30,West,Technology,Consumer,1181.13,0.0,656.324795,430.962340,750.167660
29,ORD_10029,CUST_112,2024-01-30,East,Technology,Consumer,1154.10,0.1,656.324795,413.868837,740.231163
61,ORD_10061,CUST_124,2024-03-02,West,Technology,Consumer,1132.24,0.0,656.324795,430.962340,701.277660
142,ORD_10142,CUST_149,2024-05-22,East,Technology,Consumer,1175.96,0.2,656.324795,413.868837,762.091163

In [274]:
df['sales_amount'].describe()

count     200.000000
mean      399.738950
std       300.340069
min        10.580000
25%       144.337500
50%       341.795000
75%       537.065000
max      1189.680000
Name: sales_amount, dtype: float64